export { default as logoSrc } from './logo.png';
export { default as arrowBackSrc } from './arrow-back.svg';
export { default as chevronDownSrc } from './chevron-down.svg';
export { default as plusSrc } from './plus.svg';
export { default as greySonic } from './grey-sonic.svg';
export { default as greyPlug } from './grey-plug.svg';
export { default as infoSrc } from './info.svg';
export { default as closeSrc } from './close.svg';
export { default as settingSrc } from './settings.svg';
